-- =========================================================
-- MASTER ADMIN AI CHATBOT: DYNAMIC SQL EXECUTION
-- =========================================================

-- Function to execute SELECT queries generated by AI
-- This is restricted to SELECT only and uses regex to block DML/DDL
CREATE OR REPLACE FUNCTION public.execute_ai_select(sql_query text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with privileges of creator
AS $$
DECLARE
    result json;
    clean_query text;
BEGIN
    clean_query := trim(sql_query);
    
    -- 1. Remove trailing semicolon if present
    IF clean_query LIKE '%;' THEN
        clean_query := left(clean_query, length(clean_query) - 1);
    END IF;

    -- 2. Robust SELECT-only check (handles leading whitespace and comments)
    -- This regex looks for 'SELECT' as the first non-comment/whitespace word
    IF NOT (clean_query ~* '^\s*(?:--.*?\n|\s)*SELECT\M') THEN
        RAISE EXCEPTION 'Only SELECT queries are allowed for AI Assistant.';
    END IF;

    -- 3. Block restricted keywords (DML, DDL, etc.)
    -- Using regex to find forbidden words as whole words
    IF clean_query ~* '\m(insert|update|delete|drop|truncate|alter|grant|revoke|create|replace|upsert|vacuum|analyze|explain|copy)\M' THEN
        RAISE EXCEPTION 'Restricted operation detected in AI query.';
    END IF;

    -- 4. Execute and aggregate to JSON
    BEGIN
        EXECUTE format('SELECT json_agg(row_to_json(t)) FROM (%s) t', clean_query) INTO result;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION 'Database Error: %', SQLERRM;
    END;

    -- Handle null results (empty set)
    IF result IS NULL THEN
        RETURN '[]'::json;
    END IF;

    RETURN result;
END;
$$;

-- Grant execution to authenticated users (RLS in the API will restrict to Master Admin)
GRANT EXECUTE ON FUNCTION public.execute_ai_select(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.execute_ai_select(text) TO service_role;

COMMENT ON FUNCTION public.execute_ai_select(text) IS 'Executes dynamic SELECT queries for the Master Admin AI Chatbot with strict safety checks.';
